name: Build iOS Tweak

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Tweak
    runs-on: ubuntu-latest
    container:
      image: theos/theos:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Package
        run: make package
