name: Build iOS Tweak

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
      
      - name: Build Tweak
        run: |
          export THEOS=$(ls -d /home/runner/theos)
          export PATH=$THEOS/bin:$PATH
          make package
