name: Build iOS Tweak

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Theos
        run: |
          export THEOS=/home/runner/theos
          # Sử dụng biến môi trường để bỏ qua việc nhập mật khẩu và sudo
          export THEOS_INSTALL_METHOD=automatic
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
      
      - name: Build Tweak
        run: |
          export THEOS=/home/runner/theos
          export PATH=$THEOS/bin:$PATH
          make package
